name: dchs_motion_sensors
description: Flutter plugin for accessing the Android and iOS accelerometer, gyroscope, magnetometer, and orientation sensors.
# pub.dev using `flutter pub publish`.
version: 2.0.2
homepage: https://github.com/dariocavada/dchs_motion_sensors

environment:
  sdk: '>=3.11.0 <4.0.0'
  flutter: '>=3.41.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: finaldev.motion_sensors
        pluginClass: MotionSensorsPlugin
      ios:
        pluginClass: SwiftMotionSensorsPlugin
